### ISSUE TITLE
Needs to readapt to the latest version of Pyrogram

### ISSUE THREAD

**Issue by erbanku** [gurland/telegram-delete-all-messages#43]
This script is currently no longer valid and needs to be re-adapted to the latest version of Pyrogram.

**Comment by xanoni** [comment]
That's true... here is the output I'm seeing ... it goes on and on and on

```
[...]
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 24s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 24s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 24s (required by "messages.GetDialogs")
[client] Sleeping for 20s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 24s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 23s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 25s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 27s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 18s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 26s (required by "messages.GetDialogs")
[client] Sleeping for 24s (required by "messages.GetDialogs")
[client] Sleeping for 24s (required by "messages.GetDialogs")
[...]
```

**Comment by xanoni** [comment]
Has someone worked around this by any chance and could share the fix?

**Comment by xanoni** [comment]
do we have a fix to this?

**Comment by erbanku** [comment]
> do we have a fix to this?

Not yet.
But it seems fixed by itself, I can use normally now

**Comment by xanoni** [comment]
>  But it seems fixed by itself, I can use normally now

Not for me ... still seeing the same from output from above. What about others?

**Comment by xanoni** [comment]
```bash
$ pip3 freeze
async-lru==1.0.2
pkg_resources==0.0.0
pyaes==1.6.1
Pyrogram==1.2.9
PySocks==1.7.1
TgCrypto==1.2.2
```

**Comment by xanoni** [comment]
By the way, I'm not convinced that is related to the Pyrogram version ... the last update of Pyrogram was April:

https://pypi.org/project/Pyrogram/

Also, none of the other dependencies have been bumped recently.
